apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: default
# DeploymentSpec object
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysql
  #PodTemplateSpec object
  template:
    metadata:
      name: mysql
      labels:
        name: mysql
    #PodSpec object
    spec:
      containers:
        - name: mysql
          image: mysql
          ports:
          - containerPort: 3306
          env:
          - name: MYSQL_DATABASE
            value: operations
          - name: MYSQL_ROOT_PASSWORD
            value: secret
          - name: MYSQL_USER
            value: root